# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
#-   repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v3.2.0
#    hooks:
#    -   id: trailing-whitespace
#    -   id: end-of-file-fixer
#    -   id: check-yaml
#    -   id: check-toml
#    -   id: check-json
#    -   id: check-added-large-files
#    -   id: check-merge-conflict
#    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: 
        - flake8-bugbear
        - flake8-cognitive-complexity
#        - flake8-expression-complexity
        - flake8-simplify
-   repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        name: isort (python)
    -   id: isort
        name: isort (cython)
        types: [cython]
    -   id: isort
        name: isort (pyi)
        types: [pyi]
