version: '3'
services:
  adonis_blue:
    build:
      context: .
    image: ${ADONIS_BLUE_IMAGE:-butterfly/adonis_blue}
    env_file:
      - ./src/adonis_blue/.env
    container_name: adonis_blue
    restart: always
